# Generated by Django 3.1.1 on 2020-09-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('civil_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.civil_user')),
                ('soldier_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.soldier_user')),
            ],
        ),
    ]
